# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8c7f115632fab26064d409a104f91427f06dd2df3dc43918247b36859f3fe41721de085b87ac36bd0e7a12c30cd5cbd7d76121a150fe11e64a15724edbc6fea

test:
  secret_key_base: 003906dbadf4acece9a060a99be0b323a68cba605f95afce3b8b2776c12c24725362539abeadb445976c2d25e05c2e18cd8e87d7f42d2ffb8e0a2fc94e092e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
